image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  DOCKER_HOST: tcp://35.187.39.55:2376/
  DOCKER_DRIVER: overlay2
#  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build

before_script: 
  - docker info

build_job:
  stage: build
  script:
    - docker build -t xunder/reddit .
