image: docker:19.03.1

variables:
  DOCKER_HOST: tcp://docker:2376/

services:
  - docker:19.03.1-dind

stages:
  - build

before_script: 
  - docker info

build_job:
  stage: build
  script:
    - docker build -t xunder/reddit .
