version: '3.3'
services:
  post_db:
    image: mongo:${VER_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
        - comment_db
  ui:
    image: ${USERNAME}/ui:${VER_UI}
    ports:
      - ${REDDIT_PORT}:9292/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${VER_POST}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAME}/comment:${VER_COMMENT}
    networks:
      - back_net
      - front_net
    
volumes:
  post_db:
  
networks:
  back_net:
    ipam:
      config:
      - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
      - subnet: 10.0.1.0/24
