version: '3.3'
services:
  post_db:
    image: mongo:${VER_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
        - comment_db
  ui:
    image: ${USERNAME}/ui:${VER_UI}
    ports:
      - ${REDDIT_PORT}:9292/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${VER_POST}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAME}/comment:${VER_COMMENT}
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${USERNAME}/prometheus:${VER_PROMETHEUS}
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net

  mongodb_exporter:
#    image: kubedb/mongodb_exporter:v1.0.0
#    image: skyscrapers/mongodb-exporter
    image: xunder/mongodb_exporter:1.0
    environment:
      - MONGODB_URI=mongodb://post_db:27017
    networks:
      - back_net

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.15.1
    networks:
      - back_net
      - front_net
    
volumes:
  post_db:
  prometheus_data:
  
networks:
  back_net:
    ipam:
      config:
      - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
      - subnet: 10.0.1.0/24
