FROM alpine:3.9.4
RUN apk --no-cache update && apk add --no-cache ruby-full ruby-dev build-base mongodb git \
    && mkdir -p /data/db \
    && gem install bundler:1.17.2 --no-ri --no-rdoc \
    && git clone -b monolith https://github.com/express42/reddit.git

#ENV APP_HOME /app
#RUN mkdir $APP_HOME
WORKDIR /reddit

#COPY Gemfile* $APP_HOME/
RUN bundle update --bundler && bundle install
#COPY . $APP_HOME

#ENV COMMENT_DATABASE_HOST comment_db
#ENV COMMENT_DATABASE comments

CMD ["mongod"]
#CMD ["puma"]
