version: '3.3'
services:
  comment:
    command: "puma --debug -w 2"
    volumes:
      - type: bind
        source: ./comment
        target: /app
  ui:
    command: "puma --debug -w 2"
    volumes:
      - type: bind
        source: ./ui
        target: /app
  post:
    volumes:
      - type: bind
        source: ./post-py
        target: /app
